import PixiMultiText from "@/components/PixiMultiText";
import { Stage } from "@pixi/react";
import { Meta, StoryObj } from "@storybook/react";
import { TextStyle } from "pixi.js";

const meta: Meta<typeof PixiMultiText> = {
  component: PixiMultiText,
  parameters: {
    layout: "centered",
  },
  decorators: [
    (Story) => {
      return (
        <Stage width={1024} height={1024} options={{ backgroundAlpha: 0 }}>
          <Story />
        </Stage>
      );
    },
  ],
};

export default meta;

type Story = StoryObj<typeof PixiMultiText>;

export const BeastWood: Story = {
  args: {
    text: "Hello World",
    species: [
      {
        style: new TextStyle({
          dropShadow: true,
          dropShadowAlpha: 0.3,
          dropShadowAngle: 4.5,
          dropShadowBlur: 6,
          dropShadowDistance: 0,
          fill: "#ce0000",
          fontFamily: "Primary",
          fontSize: 110,
          fontWeight: "bold",
          lineJoin: "round",
          padding: 8,
          stroke: "#9b0000",
          strokeThickness: 4,
        }),
        offset: { y: 4 },
      },
      {
        style: new TextStyle({
          fill: "#e80000",
          fontFamily: "Primary",
          fontSize: 110,
          fontWeight: "bold",
          lineJoin: "round",
          padding: 8,
          stroke: "#a40000",
          strokeThickness: 4,
        }),
        offset: { y: 2 },
      },
      {
        style: new TextStyle({
          fill: "#f3cf41",
          fontFamily: "Primary",
          fontSize: 110,
          fontWeight: "bold",
          lineJoin: "round",
          padding: 8,
          stroke: "white",
        }),

        offset: { y: 2 },
      },
      {
        style: new TextStyle({
          fill: ["#ffe240", "#ff8409"],
          fontFamily: "Primary",
          fontSize: 110,
          fontWeight: "bold",
          lineJoin: "round",
          padding: 8,
          stroke: "#ffda46",
          strokeThickness: 3,
        }),
      },
    ],
  },
};

export const BeastWoodBigWin: Story = {
  args: {
    text: "Hello World",
    species: [
      {
        style: new TextStyle({
          dropShadow: true,
          dropShadowAlpha: 0.4,
          dropShadowAngle: 1,
          dropShadowBlur: 14,
          dropShadowColor: "#11071c",
          dropShadowDistance: 12,
          fill: "#190c41",
          fontFamily: ['"CCHeroSandwichMeat"', '"Primary"'],
          fontSize: 90,
          lineJoin: "round",
          miterLimit: 40,
          padding: 30,
          stroke: "#16082b",
          strokeThickness: 23,
        }),
        offset: { y: 10, x: -6 },
      },
      {
        style: new TextStyle({
          dropShadowAlpha: 0.8,
          dropShadowAngle: 0.9,
          dropShadowBlur: 5,
          dropShadowColor: "#160f4d",
          dropShadowDistance: 1,
          fill: ["#34287d", "#5955dd"],
          fontFamily: ['"CCHeroSandwichMeat"', '"Primary"'],
          fontSize: 90,
          lineJoin: "round",
          padding: 30,
          stroke: "#4641a4",
          strokeThickness: 23,
        }),
        offset: { y: 0, x: -8 },
      },
      {
        style: new TextStyle({
          dropShadow: true,
          dropShadowAngle: 1,
          dropShadowBlur: 1,
          dropShadowColor: "#452b8c",
          dropShadowDistance: 1,
          fill: "#31215f",
          fontFamily: ['"CCHeroSandwichMeat"', '"Primary"'],
          fontSize: 90,
          lineJoin: "round",
          padding: 30,
          stroke: "#31215f",
          strokeThickness: 23,
        }),
        offset: { y: 3, x: -8 },
      },
      {
        style: new TextStyle({
          dropShadow: true,
          dropShadowAlpha: 0.9,
          dropShadowAngle: 1.2,
          dropShadowBlur: 8,
          dropShadowColor: "#080317",
          dropShadowDistance: 1,
          fill: "#7a3100",
          fontFamily: ['"CCHeroSandwichMeat"', '"Primary"'],
          fontSize: 90,
          lineJoin: "round",
          padding: 30,
          stroke: "#4d1f00",
          strokeThickness: 10,
        }),
        offset: { y: 10 },
      },
      {
        style: new TextStyle({
          dropShadowAlpha: 0.8,
          dropShadowAngle: 0.9,
          dropShadowBlur: 5,
          dropShadowColor: "#331b00",
          dropShadowDistance: 1,
          fill: "#7a3100",
          fontFamily: ['"CCHeroSandwichMeat"', '"Primary"'],
          fontSize: 90,
          lineJoin: "round",
          padding: 30,
          stroke: "#612700",
          strokeThickness: 10,
        }),
        offset: { y: 10 },
      },
      {
        style: new TextStyle({
          dropShadowAlpha: 0.8,
          dropShadowAngle: 0.9,
          dropShadowBlur: 5,
          dropShadowColor: "#331b00",
          dropShadowDistance: 1,
          fill: "#7a3100",
          fontFamily: ['"CCHeroSandwichMeat"', '"Primary"'],
          fontSize: 90,
          lineJoin: "round",
          padding: 30,
          stroke: "#752f00",
          strokeThickness: 10,
        }),
        offset: { y: 10 },
      },
      {
        style: new TextStyle({
          dropShadowAlpha: 0.8,
          dropShadowAngle: 0.9,
          dropShadowBlur: 5,
          dropShadowColor: "#331b00",
          dropShadowDistance: 1,
          fill: "#9d3f01",
          fontFamily: ['"CCHeroSandwichMeat"', '"Primary"'],
          fontSize: 90,
          lineJoin: "round",
          padding: 30,
          stroke: "#803300",
          strokeThickness: 8,
        }),
        offset: { y: 8 },
      },
      {
        style: new TextStyle({
          dropShadowAlpha: 0.8,
          dropShadowAngle: 0.9,
          dropShadowBlur: 5,
          dropShadowColor: "#331b00",
          dropShadowDistance: 1,
          fill: "#9d3f01",
          fontFamily: ['"CCHeroSandwichMeat"', '"Primary"'],
          fontSize: 90,
          lineJoin: "round",
          padding: 30,
          stroke: "#9d3f01",
          strokeThickness: 6,
        }),
        offset: { y: 6 },
      },
      {
        style: new TextStyle({
          dropShadowAlpha: 0.8,
          dropShadowAngle: 0.9,
          dropShadowBlur: 5,
          dropShadowColor: "#331b00",
          dropShadowDistance: 1,
          fill: "#c04e02",
          fontFamily: ['"CCHeroSandwichMeat"', '"Primary"'],
          fontSize: 90,
          lineJoin: "round",
          padding: 30,
          stroke: "#c04e02",
          strokeThickness: 4,
        }),
        offset: { y: 4 },
      },
      {
        style: new TextStyle({
          dropShadowAlpha: 0.8,
          dropShadowAngle: 0.9,
          dropShadowBlur: 5,
          dropShadowColor: "#331b00",
          dropShadowDistance: 1,
          fill: "#e76612",
          fontFamily: ['"CCHeroSandwichMeat"', '"Primary"'],
          fontSize: 90,
          lineJoin: "round",
          padding: 30,
          stroke: "#e76612",
          strokeThickness: 2,
        }),
        offset: { y: 2 },
      },
      {
        style: new TextStyle({
          dropShadowAngle: 1.6,
          dropShadowColor: "#561c00",
          fill: "#fff9a8",
          fillGradientStops: [0.3, 0.5, 0.53, 0.57, 0.8],
          fontFamily: ['"CCHeroSandwichMeat"', '"Primary"'],
          fontSize: 90,
          lineJoin: "round",
          miterLimit: 0,
          padding: 30,
          stroke: "#eb9d56",
          // offsetX: -1,
          // offsetY: -2
        }),
        offset: { x: -1, y: -2 },
      },
      {
        style: new TextStyle({
          dropShadowAngle: 1.6,
          dropShadowColor: "#561c00",
          fill: "#fffbc7",
          fillGradientStops: [0.3, 0.5, 0.53, 0.57, 0.8],
          fontFamily: ['"CCHeroSandwichMeat"', '"Primary"'],
          fontSize: 90,
          lineJoin: "round",
          miterLimit: 0,
          padding: 30,
          stroke: "#eb9d56",
          // offsetY: -2
        }),
        offset: { y: -2 },
      },
      {
        style: new TextStyle({
          dropShadowAngle: 1.6,
          dropShadowColor: "#561c00",
          fill: ["#ffc852", "#fefabe", "#f7af4b", "#ff9214", "#ffe485"],
          fillGradientStops: [0.3, 0.5, 0.52, 0.59, 0.8],
          fontFamily: ['"CCHeroSandwichMeat"', '"Primary"'],
          fontSize: 90,
          lineJoin: "round",
          miterLimit: 0,
          padding: 30,
          stroke: "#eb9d56",
        }),
      },
      {
        style: new TextStyle({
          dropShadowAngle: 1.6,
          dropShadowColor: "#561c00",
          fill: ["#ffc852", "#fefabe", "#f7af4b", "#ff9214", "#ffe485"],
          fillGradientStops: [0.22, 0.35, 0.53, 0.6, 0.8],
          fontFamily: ['"CCHeroSandwichMeat"', '"Primary"'],
          fontSize: 90,
          lineJoin: "round",
          miterLimit: 0,
          padding: 30,
          stroke: "#eb9d56",
        }),
      },
    ],
  },
};

export const EasternEmeraldsMV: Story = {
  args: {
    text: "Hello World",
    species: [
      {
        style: new TextStyle({
          align: "center",
          dropShadow: true,
          dropShadowAlpha: 0.4,
          dropShadowAngle: 1.4,
          dropShadowBlur: 7,
          dropShadowDistance: 6,
          fill: "#610000",
          fontFamily: ['"Fengo"', '"Primary"'],
          fontSize: 50,
          lineHeight: 122,
          lineJoin: "round",
          padding: 20,
          stroke: "#600100",
          wordWrapWidth: 500,
        }),
        offset: { y: 3 },
      },
      {
        style: new TextStyle({
          align: "center",
          dropShadowAngle: 0,
          dropShadowBlur: 6,
          dropShadowDistance: 0,
          fill: "#3d2800",
          fontFamily: ['"Fengo"', '"Primary"'],
          fontSize: 50,
          lineHeight: 122,
          lineJoin: "round",
          padding: 20,
          stroke: "#572700",
          strokeThickness: 3,
          wordWrapWidth: 500,
        }),
        offset: { y: 5 },
      },
      {
        style: new TextStyle({
          align: "center",
          dropShadow: true,
          dropShadowAlpha: 0.5,
          dropShadowAngle: 0,
          dropShadowBlur: 3,
          dropShadowDistance: 0,
          fill: "#610000",
          fontFamily: ['"Fengo"', '"Primary"'],
          fontSize: 50,
          lineHeight: 122,
          lineJoin: "round",
          padding: 20,
          stroke: "#600100",
          strokeThickness: 6,
          wordWrapWidth: 500,
        }),
        offset: { y: 3 },
      },
      {
        style: new TextStyle({
          align: "center",
          dropShadowAlpha: 0.4,
          dropShadowAngle: 0.9,
          dropShadowBlur: 10,
          dropShadowColor: "#2c0200",
          dropShadowDistance: 7,
          fill: ["#ecdc4e", "#eca427"],
          fontFamily: ['"Fengo"', '"Primary"'],
          fontSize: 50,
          lineHeight: 122,
          lineJoin: "round",
          padding: 20,
          stroke: "#a9590a",
          strokeThickness: 3,
          wordWrapWidth: 500,
        }),
        offset: { y: 3 },
      },
      {
        style: new TextStyle({
          align: "center",
          dropShadowAlpha: 0.4,
          dropShadowAngle: 0.9,
          dropShadowBlur: 10,
          dropShadowColor: "#2c0200",
          dropShadowDistance: 7,
          fill: ["#eddf52", "#eca427"],
          fontFamily: ['"Fengo"', '"Primary"'],
          fontSize: 50,
          lineHeight: 50,
          lineJoin: "round",
          padding: 20,
          stroke: "#a9590a",
          wordWrapWidth: 500,
        }),
        offset: { y: 37, x: 2 },
      },
      {
        style: new TextStyle({
          align: "center",
          dropShadowAngle: 1.6,
          dropShadowColor: "#561c00",
          fill: ["#b97900", "#ffff6b", "#ffff8d", "#ffd657", "#b97900"],
          fillGradientStops: [0.1, 0.48, 0.56, 0.7, 0.8],
          fontFamily: ['"Fengo"', '"Primary"'],
          fontSize: 50,
          lineHeight: 50,
          lineJoin: "round",
          miterLimit: 0,
          padding: 20,
          stroke: "#eb9d56",
          wordWrapWidth: 500,
        }),
        offset: { y: 36, x: 2 },
      },
    ],
  },
};

export const SakuraEpicBloomBigWin: Story = {
  args: {
    text: "Hello World",
    species: [
      {
        style: new TextStyle({
          dropShadow: true,
          dropShadowAlpha: 0.7,
          dropShadowAngle: 1.6,
          dropShadowBlur: 9,
          dropShadowDistance: 6,
          fill: ["#fbfad3", "#feb146", "#b86a2e"],
          fillGradientStops: [0.3, 0.7, 0.9],
          fontFamily: ['"Fengo"', '"Primary"'],
          fontSize: 115,
          strokeThickness: 12,
        }),
        offset: { y: 5 },
      },
      {
        style: new TextStyle({
          dropShadowAlpha: 0.7,
          dropShadowAngle: 1.6,
          dropShadowBlur: 9,
          dropShadowDistance: 10,
          fill: ["#fbfad3", "#feb146", "#b86a2e"],
          fillGradientStops: [0.3, 0.7, 0.9],
          fontFamily: ['"Fengo"', '"Primary"'],
          fontSize: 115,
          stroke: "#f34127",
          strokeThickness: 12,
        }),
        offset: { y: -1 },
      },
      {
        style: new TextStyle({
          dropShadowAlpha: 0.7,
          dropShadowAngle: 1.6,
          dropShadowBlur: 9,
          dropShadowDistance: 10,
          fill: ["#fbfad3", "#feb146", "#b86a2e"],
          fillGradientStops: [0.3, 0.7, 0.9],
          fontFamily: ['"Fengo"', '"Primary"'],
          fontSize: 115,
          stroke: "#520606",
          strokeThickness: 12,
        }),
        offset: { y: 5 },
      },
      {
        style: new TextStyle({
          fill: ["#fbfad3", "#feb146", "#b86a2e"],
          fillGradientStops: [0.3, 0.7, 0.9],
          fontFamily: ['"Fengo"', '"Primary"'],
          fontSize: 115,
          stroke: "#ab0b0e",
          strokeThickness: 11,
        }),
        offset: { y: 1 },
      },
      {
        style: new TextStyle({
          fill: ["#eeae3c", "#ffe680", "#feffdb", "#f5b553", "#c66f24"],
          fontFamily: ['"Fengo"', '"Primary"'],
          fontSize: 115,
          stroke: "#ff6251",
          strokeThickness: 5,
        }),
        offset: { y: 6, x: 3 },
      },
      {
        style: new TextStyle({
          fill: ["#eeae3c", "#ffe680", "#feffdb", "#f5b553", "#c66f24"],
          fontFamily: ['"Fengo"', '"Primary"'],
          fontSize: 115,
          stroke: "#5a1c00",
          strokeThickness: 5,
        }),
        offset: { y: 5, x: 3 },
      },
    ],
  },
};

export const WildCauldron: Story = {
  args: {
    text: "Hello World",
    species: [
      {
        style: new TextStyle({
          dropShadowAlpha: 0.4,
          dropShadowAngle: 0.9,
          dropShadowBlur: 10,
          dropShadowColor: "#1b012c",
          dropShadowDistance: 7,
          fill: "#7d3c00",
          fontFamily: "Primary",
          fontSize: 200,
          fontStyle: "italic",
          lineJoin: "round",
          padding: 20,
          stroke: "#3c110b",
          strokeThickness: 24,
        }),
        offset: { x: 1, y: 1 },
      },
      {
        style: new TextStyle({
          dropShadowAlpha: 0.4,
          dropShadowAngle: 0.9,
          dropShadowBlur: 10,
          dropShadowColor: "#2c0200",
          dropShadowDistance: 7,
          fill: "#5e2d00",
          fontFamily: "Primary",
          fontSize: 200,
          fontStyle: "italic",
          lineJoin: "round",
          padding: 20,
          stroke: "#7b3615",
          strokeThickness: 16,
        }),
        offset: { x: -1, y: 1 },
      },
      {
        style: new TextStyle({
          dropShadowAlpha: 0.4,
          dropShadowAngle: 0.9,
          dropShadowBlur: 10,
          dropShadowColor: "#2c0200",
          dropShadowDistance: 7,
          fill: "#38005e",
          fontFamily: "Primary",
          fontSize: 200,
          fontStyle: "italic",
          lineJoin: "round",
          padding: 20,
          stroke: "#450c0c",
          strokeThickness: 16,
        }),
        offset: { x: 1, y: 3 },
      },
      {
        style: new TextStyle({
          dropShadowAlpha: 0.4,
          dropShadowAngle: 0.9,
          dropShadowBlur: 10,
          dropShadowColor: "#2c0200",
          dropShadowDistance: 7,
          fill: "#ffe479",
          fontFamily: "Primary",
          fontSize: 200,
          fontStyle: "italic",
          lineJoin: "round",
          padding: 20,
          stroke: "#402000",
        }),
        offset: { y: 16, x: 9 },
      },
      {
        style: new TextStyle({
          dropShadow: true,
          dropShadowAngle: 0.9,
          dropShadowBlur: 5,
          dropShadowColor: "#210112",
          dropShadowDistance: 1,
          fill: ["#9f3400", "#ee4811"],
          fontFamily: "Primary",
          fontSize: 200,
          fontStyle: "italic",
          lineJoin: "round",
          padding: 20,
          stroke: "#402000",
        }),
        offset: { x: 11, y: 21 },
      },
      {
        style: new TextStyle({
          dropShadowAngle: 1.6,
          dropShadowColor: "#561c00",
          fill: ["#e5af12", "#fcd834", "#e7a82e", "#ffeb52"],
          fillGradientStops: [0.3, 0.5, 0.51, 0.7],
          fontFamily: "Primary",
          fontSize: 200,
          fontStyle: "italic",
          lineJoin: "round",
          miterLimit: 0,
          padding: 20,
          stroke: "#eb9d56",
        }),
        offset: { x: 9, y: 19 },
      },
    ],
  },
};
