/*
  Auto-generated by Spline
*/
import Spline from "@splinetool/react-spline";
import type { Meta, StoryObj } from "@storybook/react";

const meta: Meta<typeof Spline> = {
  component: Spline,
  parameters: {
    layout: "centered",
  },
};

export default meta;

type Story = StoryObj<typeof Spline>;

export const Normal: Story = {
  args: {
    scene: "/scene.splinecode",
  },
};
